src/js/components/TextInput.js
src/js/login.js
src/js/register.js

Closes COM-###
1 - Since this require credentials to send the registration/confirmation email set. Set in `config.edn` `(auto-validate? flag to true)`
2- Register new user 
3- Login in with new user credentials
Should be able to login 
---

SER-22 Fix registration

---

src/clj/comimo/db/projects.clj

Convert to arrays (Java) from Clojure vectors for JDBC driver (SQL) 
User
1. Create a project with subscribed or selected municipalities 
The project should be created

SER-23 Fix project creation

---

src/js/home/SearchPanel.js

User
1. Go to search tab 
2. Search for municipality (ex. LETICIA)
The search should work, returning result that is clickable (that focus the map) 
---

SER-24 Fix municipality search

---

package.json
src/clj/comimo/git.clj
src/clj/comimo/views.clj
src/js/admin/admin.js
src/js/collect/collect.js
src/js/components/Header.js
src/js/components/PageLayout.js
src/js/home/home.js
src/js/passwordRequest.js

Allow to use git tags for versioning when deploying (especially to production). 
Closes SER-27
1. Add git tag to repo and push it (must start with prefix: prod-) 
2. Run the app 
You should see the latest tag that starts with prod beeing used as version underneath the logo in the app header.

SER-27 Add calendar versioning to comimo

---

src/clj/comimo/email.clj
src/js/passwordRequest.js

This fix allow to send emails to reset the password.
Closes COM-###

Fix reset password form testing

---

resources/public/locale/es.json
src/js/components/PageLayout.js

Fix language changing in home page

---

src/js/home/InfoPopupContent.js

Puts the current label on current prediction map info popup layer.
Closes COM-###

Fix popup label

---

src/js/home/SubscribePanel.js

Fix when deleting subscription
Closes COM-###

Fix deleting subscription

---

package.json
resources/public/locale/en.json
resources/public/locale/es.json
src/js/components/Button.js
src/js/components/Modal.js
src/js/home/ReportMinesPanel.js
src/js/home/home.js

Creates a new Modal component and uses it to add confirmation to reporting mines. Fixes the reporting mine tooltip and icon. 
Closes COM-53
The mine reporting feature should work normally
Some examples of the Modal component in use:

SER-53 Add a Modal component and add confirmation to reporting mines

---

resources/public/locale/en.json
resources/public/locale/es.json
src/js/admin/admin.js
src/js/components/SvgIcon.js

Closes COM-54
All features on the admin page should work normally.

SER-54 Clean up the logic and UI on the admin page

---

resources/public/css/comimo_global.css
resources/public/locale/en.json
resources/public/locale/es.json
src/js/admin.jsx
src/js/collect/NavBar.jsx
src/js/components/Button.jsx
src/js/components/Header.jsx
src/js/components/IconButton.jsx
src/js/components/Modal.jsx
src/js/components/NICFIControl.jsx
src/js/components/ProjectCard.jsx
src/js/components/Search.jsx
src/js/constants.js
src/js/home/DownloadPanel.jsx
src/js/home/FilterPanel.jsx
src/js/home/LoginMessage.jsx
src/js/home/ReportMinesPanel.jsx
src/js/home/SubscribePanel.jsx
src/js/home/ValidatePanel.jsx
src/js/login.jsx
src/js/passwordRequest.jsx
src/js/passwordReset.jsx
src/js/register.jsx
src/js/userAccount.jsx

Updates the Button component to have a disabled state, a hover state, and a default/secondary coloring. Updates all instances of the Button component across the site to use this. Added localization to the NavBar on the CEO lite validation page.
Closes SER-243
All buttons should work normally.

SER-243 Update the Button component and use the new component across the site

---

resources/public/locale/en.json
resources/public/locale/es.json
src/js/home.jsx
src/js/home/HomeMap.jsx
src/js/passwordRequest.jsx
src/js/register.jsx

Refactor register and request password pages and add site banners

SER-236 Refactor register and request password pages and add site banners

---

resources/public/locales/en/translation.json
resources/public/locales/es/translation.json
src/js/components/Divider.jsx
src/js/components/HeaderLabel.jsx
src/js/components/Modal.jsx
src/js/components/NICFIControl.jsx
src/js/components/Search.jsx
src/js/components/Select.jsx
src/js/components/TextInput.jsx
src/js/components/ToolCard.jsx
src/js/constants.js
src/js/home/DownloadPanel.jsx
src/js/home/HomeMap.jsx
src/js/home/LayersPanel.jsx
src/js/home/StatsPanel.jsx
src/js/home/SubscribePanel.jsx
src/js/home/ValidatePanel.jsx
src/js/register.jsx
src/js/userAccount.jsx

Tons of UI updates. Best explained in the screenshots section.
Closes SER-273
---

SER-273 Lots of UI updates

---

resources/public/css/comimo_global.css
src/js/components/ToolCard.jsx
src/js/constants.js
src/js/home/LayersPanel.jsx

Adds layer colors to the slider and check box elements in the layer selection tool.
Closes SER-111
On Chrome:
On FireFox:

SER-111 Add layer colors to the UI

---

resources/public/css/comimo_global.css
resources/public/locales/en/translation.json
src/js/collect.jsx
src/js/collect/InputNumber.jsx
src/js/collect/NavBar.jsx
src/js/collect/SvgButton.jsx
src/js/components/Button.jsx
src/js/components/DeleteButton.jsx
src/js/components/IconButton.jsx
src/js/components/LanguageButtons.jsx
src/js/components/SvgIcon.jsx

Updates the UI (and adds new components) of the nav bar on the collect page.
TODO:
Closes SER-274

SER-274 WIP update the nav bar on the collect page

---

resources/public/css/comimo_global.css
resources/public/locales/en/translation.json
resources/public/locales/es/translation.json
src/js/collect/NavBar.jsx

Add a button to clear the mine/no mine selection on a given plot
Closes SER-94

SER-94 Add clear button to nav bar

---

src/js/collect.jsx
src/js/collect/CollectMap.jsx
src/js/components/Header.jsx
src/js/components/PageLayout.jsx
src/js/components/Search.jsx
src/js/home.jsx
src/js/home/DownloadPanel.jsx
src/js/home/HomeMap.jsx
src/js/home/SubscribePanel.jsx

The search tool wasn't fully working on the collect page. This PR fixes that as well as does some other code tidying.
Closes SER-277
The Search tool should work everywhere, including the Collect page.

SER-277 Fix the search tool on the collect page

---

src/js/collect/CollectDownload.jsx

Fix download panel title on collect page

---

resources/public/locales/en/translation.json
resources/public/locales/es/translation.json
src/js/components/DeleteButton.jsx
src/js/components/Header.jsx
src/js/components/Search.jsx
src/js/components/Select.jsx
src/js/components/ToolCard.jsx
src/js/home/DownloadPanel.jsx
src/js/home/SubscribePanel.jsx

Co-authored-by: Oliver Baldwin Edwards <Oliver-BE@users.noreply.github.com>
Closes SER-###
1.
---

Fix reported bugs with enhancements

---

src/clj/comimo/db/plots.clj
src/js/admin.jsx
src/js/collect.jsx
src/sql/functions/plots.sql
src/sql/tables/all.sql

Fixes the following bugs on the admin page:
* Longitude column not populated
* Institution column not populated
* Added back in the label column
Closes SER-280

SER-280 Fixes to the admin page

---

src/js/components/SvgIcon.jsx
src/js/components/UserDropdown.jsx

Adding a log out button to the user dropdown menu
Closes SER-287

SER-287 Add log out to user dropdown menu

---

src/js/verifyUser.jsx

Closes SER-279
You should be able to confirm new user following the link (to test use only the path with localhost:8080 as the domain name)

SER-279 Fix registration bug

---

src/js/home.jsx
src/js/home/StatsPanel.jsx

Co-authored-by: Sif Biri <sif@fastmail.com>
Fix the stats panel

SER-286 Fix stats panel

---

src/js/home/HomeMap.jsx

Fix issue when layers sometimes show and sometimes not...

Fix the flickering when toggling layers

---

src/js/components/PopupMapInfo.jsx
src/js/home/HomeMap.jsx
src/js/home/InfoPopupContent.jsx
src/js/home/ReportPopupContent.jsx

SER-281 Make popup compact

---

src/js/collect.jsx
src/js/components/DropDownMenu.jsx
src/js/components/IconTextButton.jsx
src/js/components/ToolCard.jsx
src/js/home.jsx

Add some basic mobiles support. Most things work with just this added besides the `admin` page and the `navBar` when collecting (unless you turn your phone sideways).
Closes SER-291

SER-291 Add some mobile support

---

src/js/login.jsx

Fix the label on the login page

Fix password label

---

src/clj/comimo/db/projects.clj
src/sql/functions/project.sql

Closes https://sig-gis.atlassian.net/browse/SER-285
Closes SER-285

SER-285 Fix project check

---

src/js/components/Header.jsx
src/js/components/IconButton.jsx
src/js/components/IconTextButton.jsx
src/js/components/InfoModal.jsx
src/js/components/PageLayout.jsx
src/js/components/UserDropdown.jsx

Adds some small mobile UI improvements/bug fixes

Mobile UI fixes and improvements

---

src/clj/comimo/migrate.clj

Add program to move data/notify

---

src/js/home/HomeMap.jsx

Fix layers activation/selection in the home map.

Fix layers

---

src/js/home/HomeMap.jsx

Merge development into main

---

src/js/home/HomeMap.jsx

Another test at fixing the map loading time.

One more merge from development into main

---

src/clj/comimo/git.clj
src/js/collect.jsx
src/js/home.jsx

Merge dev into main

---

resources/public/css/comimo_global.css
src/js/collect/NavBar.jsx
src/js/components/SvgIcon.jsx
src/js/constants.js

Update collection bar/map style

---

src/js/home/LayersPanel.jsx

Update layers sliders

---

src/js/components/PageLayout.jsx

Make Spanish the default langauge.

COM-258  Default to Spanish language

---

config.example.edn
deps.edn
src/clj/comimo/handlers.clj
src/clj/comimo/routing.clj

Integrated Triangulum auth routing handler, created corresponding comimo handlers, and refactored.

Auth routing handler

---

deps.edn

updated triangulum

---

deps.edn

removed alias from deps.edn

---

src/clj/comimo/py_interop.clj
src/py/gee/utils.py

Adapt `getDownloadURL` to work with vector data instead of raster data

COM-376 Updated getDownloadURL

---

src/clj/comimo/py_interop.clj
src/js/home/StatsPanel.jsx
src/py/gee/utils.py

- Increased the timeout (I think the needed timeout will scale with quantity of data until Pulse does this more performantly).
- Fixed py-interop issues.
- Added relevant disclaimers to produced stats.

Accumulated fixes for stats from Andreas branch.

---

src/js/components/SvgIcon.jsx

Updates the English language icon.
Closes [COM-288](https://sig-gis.atlassian.net/browse/COM-288)
[COM-288]: https://sig-gis.atlassian.net/browse/COM-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

COM-288: Update the English language icon

---

src/js/collect/NavBar.jsx
src/js/collect/SvgButton.jsx
src/js/home/StatsPanel.jsx

To update instances where "Prev" and "Next" icon buttons are shown and ensure that the arrow icon is displayed to the right of the "Next" label.
Closes COM-298
Stats, Validation
Admin
1. Login as an administrator.
2. Click Validate CTA
3. Select a Project
4. Click "GO"
On the validation control panel:
- Observe that the "Prev" button has its icon positioned to the left.
- Observe that the "Next" button has its icon positioned to the right.
---
Admin
1. Login as an administrator.
2. Click the Statistics CTA
On the statistics panel:
- Observe that the "Prev" button has its icon positioned to the left.
- Observe that the "Next" button has its icon positioned to the right.

COM-298:  Add icon placement property on the icon button component. Update statistics and validation control panels.
