.gitignore, package.json, src/clj/comimo/handler.clj
Fixes the problem found when testing in other browsers. When refreshing or requesting the same url after loading the page, the assets don't get shown (malformed buttons and layout). Mainly has to do with one of of the wrappers in the handlers stack when getting a 403 from server. 
Closes COM-###
1.
---
=> Sif fix handlers

resources/public/locale/en.json, resources/public/locale/es.json, src/js/components/NICFIControl.js, src/js/components/Select.js, src/js/components/ToolPanel.js, src/js/home/LayersPanel.js
Separates the Planet NICFI layer from the other layers on the UI by placing it in its own section. Added some small UI tweaks and cleaned up some code in `LayersPanel.js`.
Closes SER-51
All layers should work normally.
=> SER-51 Separate Planet NICFI from other layers

src/clj/comimo/git.clj
Handle when git server returns 403 when pulling for repo tags (cap of # requests for an address)
Closes SER-100
=> SER-100 Fix dev git tags 403 issue

src/js/collect/CollectMap.js, src/js/collect/NavBar.js
Fixes an issue where zooming in on a plot label would then show duplicate plot labels. To fix this, I added a new source specifically for each plot label. Also fixes an error message that would show up when collecting by casting a number to a string for the plot number input.
Closes SER-###
Validation > Plot Label 
User
1. Create a new project 
2. Go to collect on the project
3. Select a specific plot number
4. Zoom all the way in on that plot's label
The plot label should only appear once when you zoom in and out.
=> SER-98 Fix an issue where there were multiple plot labels in each plot

src/js/components/IconButton.jsx
Adds a selected state style to the IconButtons
Closes SER-248
Selecting an IconButton on the side toolbar should change its styling (see screenshot below).
=> SER-248 Add selected state to IconButtons

src/js/components/Header.jsx, src/js/components/IconButton.jsx, src/js/components/IconTextButton.jsx
Adds a new `IconTextButton` component which combines the `IconButton` component with a text label to match the styling in Andrea's prototypes. You can optionally include a background as well as invert the border radius (as these things differ across Andrea's wireframes).
Closes SER-249
=> SER-249 Create an icon + text button component

src/js/collect.jsx, src/js/collect/CollectMap.jsx, src/js/home.jsx, src/js/home/LayersPanel.jsx
The opacity of the NICFI layer was not updating on the Collect page due to the `homeMap` being hard-coded in the `LayersPanel` component. This PR fixes that.
Closes SER-276
The opacity slider should work on the layer panel on both the home and collect pages.
=> SER-276 Fix the opacity slider on the collect page for NICFI layer

src/clj/comimo/views.clj, src/js/collect/CollectMap.jsx
Adds logic to the announcement banner so that it can be multiple lines. Speeds up the `flyTo` functionality on the collect page for quicker collection.
Closes SER-284
=> SER-284 Update announcement banner logic and speed up collection

src/js/utils.js
To not crash when calling titleCase in validation panel when regions happen to have empty strings or maybe undefined for whatever reason. 
Closes SER-###
=> SER-301 Utils functions appear to be crashing the site

config.default.edn, src/clj/comimo/db/subscriptions.clj, src/clj/comimo/email.clj
Fixes some small spacing and grammatical bugs with the email code. Adds UTF-8 encoding to emails to fix an issue where characters weren't showing up in some email clients.
Closes SER-302
=> SER-302 Some small email fixes

.gitignore, src/clj/comimo/py_interop.clj
Add caching to GEE layers and add add a three second timeout to the `py-wrapper` function.
Closes SER-316
Layers should load normally and the website shouldn't crash :sweat_smile:
=> SER-316 Add timeout to py-wrapper and cache GEE layers

src/js/components/Search.jsx, src/js/constants.js
Fixes the search functionality -- the Mapquest API endpoint changed. Also adds some nicer UI to the search functionality. 
Closes SER-309
Search > Search by Name
Visitor
1. Click on the Search button on the home screen.
2. Enter a municipality name exactly as it's spelled (e.g. Abejorral).
3. Click the Go button or Enter.
Click on the resulting pop up (which should be grey and yellow on hover). You should be taken on the map to that municipality.
---
UI before:
UI after (on hover):
=> SER-309 Fix search functionality and improve UI

.gitignore, package.json, src/js/home/ValidatePanel.jsx
Users were not able to select municipalities on mobile because of our multi select component. I tried for a while, but there was no working work-around. I thus reached for the `react-select` component, which has better UI and works on mobile.
Closes SER-311
Home > Create Project
User
1. On both mobile and desktop, try to create a project with custom municipalities.
The project should be created successfully with the selected municipalities.
---
Desktop:
Mobile:
=> SER-311 Add a new multi select component for selecting custom municipalities

src/js/collect/CollectMap.jsx, src/js/home/HomeMap.jsx
Disables map rotation and pitch to avoid confusing mobile users
Closes [COM-255](https://sig-gis.atlassian.net/browse/COM-255)
[COM-255]: https://sig-gis.atlassian.net/browse/COM-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> COM-255: Disable map rotation and pitch to avoid confusing mobile users

src/js/collect/CollectMap.jsx, src/js/home/HomeMap.jsx, src/js/home/StatsPanel.jsx
The purpose these fixes are to improve the overall appearance and rendering of the statistics charts.
The charts seemed fairly crammed up. To get around this problem, a container was added to display a single chart at time. Next/Prev were added to navigate to the other chart.
- Fixed issue where horizontal axis labels were overlapping by displaying the labels angled. Displaying a single chart at a time provided more vertical space to render the labels this way.
- The labels were also displayed angled.
- There was an ask to have the period sorted. They are now sorted by period end year
Closes [COM-254](https://sig-gis.atlassian.net/browse/COM-254)
[COM-254]: https://sig-gis.atlassian.net/browse/COM-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
=> COM-254: Improve statistics chart rendering

resources/public/locales/en.json, resources/public/locales/es.json, src/js/home/ValidatePanel.jsx
To make the project name input optional, an auto project name generation function was added to the validation panel.
As specified on the ticket, the function gathers the set of selected municipalities and concatenates the names with the following pattern: `mun_MUN1_mun_MUN2_mun_MUNNth`
- Project auto generation is set as the default
- A radio group was added to give the user the ability to edit a custom
project name if desired.
Closes [COM-259](https://sig-gis.atlassian.net/browse/COM-259)
[COM-259]: https://sig-gis.atlassian.net/browse/COM-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> COM-259: On the validation panel, make the project name input optional

src/clj/comimo/py_interop.clj
The fix increases the timeout setting to avoid hitting the timeout error.
Closes [COM-261](https://sig-gis.atlassian.net/browse/COM-261)
[COM-261]: https://sig-gis.atlassian.net/browse/COM-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> COM-261: Bugfix to avoid timeout error when downloading data

resources/public/locales/en.json, resources/public/locales/es.json, src/js/admin.jsx
Add a users data download option.  The admin page presently provides that functionality when selecting either the "Collected predictions" or "User reported mines" options. The changes reuse the behavior to download data with the "react-tabulator" module.
Closes [COM-257](https://sig-gis.atlassian.net/browse/COM-257)
[COM-257]: https://sig-gis.atlassian.net/browse/COM-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> COM-257: Add a users list data download option to the admin page

src/clj/comimo/py_interop.clj, src/py/gee/utils.py
Check if location (lat,lng) when part of layer is active to show information
=> Fix mining alerts detection popup

deps.edn
Resolve errors found when downloading confirmed layer data.
The `earthengine-api` depedency was outdated and requests made with it would call out to the outdated `v1alpha` version of the GEE API.
Resolution: `pip install --upgrade earthengine-api` on the host running the CoMiMo server.
Adds `deps.edn` updates.
Closes [COM-285](https://sig-gis.atlassian.net/browse/COM-285)
[COM-285]: https://sig-gis.atlassian.net/browse/COM-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> COM-285: Upgrade earthengine-api and other CoMiMo dependencies to resolve errors caused by GEE requests to v1alpha of earthengine.

src/clj/comimo/proxy.clj
NICFI dates for 2024 were missing, this PR solves the issue.
Due to NICFI contract ending in 2024, only a _page_size was added to retrieve the rest of the information
Closes COM-301
Validation > Imagery > nicfi dates
User
1. Select Planet NICFI as imagery
2. Select a 2024 date
3. check if it displays the imagery
=> COM-301: Bugfix: Fix issue with retrieving all nicfi dates
